stages:
  - images-list
  - images-sync
  # 代码同步
  - sync

images-list:1.27.4-0:
  stage: images-list
  image: openanolis/anolisos:7.9-x86_64
  before_script:
    - |
      cat <<EOF > /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
      # 是否开启本仓库
      enabled=1
      # 是否检查 gpg 签名文件
      gpgcheck=0
      # 是否检查 gpg 签名文件
      repo_gpgcheck=0
      gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

      EOF
  script:
    - yum install -y kubelet-1.27.4-0 kubeadm-1.27.4-0 kubectl-1.27.4-0 --disableexcludes=kubernetes --nogpgcheck
    - kubeadm config images list --kubernetes-version=v1.27.4
    - kubeadm config images list --kubernetes-version=v1.27.4 | sed 's|registry.k8s.io|registry.aliyuncs.com/google_containers|g'
    - kubeadm config images list --kubernetes-version=v1.27.4 | sed 's|registry.k8s.io|registry.aliyuncs.com/google_containers|g' | sed 's|coredns/coredns|coredns|g'
    - |
      echo "" >images.sh
      images=$(kubeadm config images list --kubernetes-version=v1.27.4 | sed 's|registry.k8s.io|registry.aliyuncs.com/google_containers|g' | sed 's|coredns/coredns|coredns|g')
      for image in $images; do
        echo "docker pull $image" >>images.sh
        if echo "$image" | grep -q "coredns"; then
          new_image="registry.jihulab.com/xuxiaowei-cloud/xuxiaowei-cloud/coredns/$(basename $image)"
          echo "docker tag $image $new_image" >>images.sh
          echo "docker push $new_image" >>images.sh
        fi
        new_image="registry.jihulab.com/xuxiaowei-cloud/xuxiaowei-cloud/$(basename $image)"
        echo "docker tag $image $new_image" >>images.sh
        echo "docker push $new_image" >>images.sh
      done
    - cat images.sh
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - images.sh
  only:
    - images-mirrors/1.27.4-0
  tags:
    - jihulab

images-sync:1.27.4-0:
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: images-sync
  needs:
    - job: images-list:1.27.4-0
      artifacts: true
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $DOCKER_PRIVATE_TOKEN $CI_REGISTRY
  script:
    - cat images.sh
    - cat images.sh | sh
  only:
    - images-mirrors/1.27.4-0
  tags:
    - jihulab

# 嵌入
include:
  # 同步代码
  - /sync.yml
