stages:
  - yum

yum:anolisos:7.9:1.24.0-0:
  stage: yum
  image: openanolis/anolisos:7.9-x86_64
  before_script:
    - |
      cat <<EOF > /etc/yum.repos.d/kubernetes.repo
      [kubernetes]
      name=Kubernetes
      baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
      # 是否开启本仓库
      enabled=1
      # 是否检查 gpg 签名文件
      gpgcheck=0
      # 是否检查 gpg 签名文件
      repo_gpgcheck=0
      gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

      EOF
    - cat /etc/yum.conf
    - sed -i 's/keepcache=0/keepcache=1/' /etc/yum.conf
    - cat /etc/yum.conf
  script:
    - yum install -y kubelet-1.24.0-0 kubeadm-1.24.0-0 kubectl-1.24.0-0 --disableexcludes=kubernetes --nogpgcheck
    - find /var/cache/yum/ -name *.rpm
    - find /var/cache/yum/ -name *.rpm -exec cp {} ./ \;
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - "*.rpm"
  only:
    - yum/1.24.0-0
  tags:
    - jihulab
