# 创建一个持久化卷（Persistent Volume）
# https://kubernetes.io/zh-cn/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolume
metadata:
  # 持久卷名称
  name: gitlab-config-pv-local
spec:
  # 持久化卷的容量为 10Gi
  capacity:
    storage: 10Gi
  # 持久化卷的访问模式为 ReadWriteMany，即多个 Pod 可以同时进行读写操作
  # https://kubernetes.io/zh-cn/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  local:
    # 需要文件夹存在
    path: /gitlab-ce-config-pv-local/etc/gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            # kubectl label nodes 储存 GitLab config 数据的节点名称 gitlab-config=local-pv
            # kubectl get node --show-labels
            - key: gitlab-config
              operator: In
              values:
                - local-pv
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitlab-config-pvc
    namespace: gitlab
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs-pv-local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /gitlab-ce-logs-pv-local/var/log/gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            # kubectl label nodes 储存 GitLab logs 数据的节点名称 gitlab-logs=local-pv
            # kubectl get node --show-labels
            - key: gitlab-logs
              operator: In
              values:
                - local-pv
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitlab-logs-pvc
    namespace: gitlab
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv-local
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  local:
    # 需要文件夹存在
    path: /gitlab-ce-data-pv-local/var/opt/gitlab
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            # kubectl label nodes 储存 GitLab data 数据的节点名称 gitlab-data=local-pv
            # kubectl get node --show-labels
            - key: gitlab-data
              operator: In
              values:
                - local-pv
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitlab-data-pvc
    namespace: gitlab
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
